# App
spring.application.name=order-system

# H2 in-memory database (no setup needed)
spring.datasource.url=jdbc:h2:mem:orderdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA ? auto creates tables from your entities
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# H2 browser console ? open http://localhost:8080/h2-console
spring.h2.console.enabled=tr